### ISSUE TITLE
mfilechooser didnt return all files in Android 11

### ISSUE THREAD

**Issue by harivenkatesh-id** [Langstra/MFileChooser#2]
cordova-plugin-mfilechooser did not return entire file lists in Android 11. 
Since getExternalStorageDirectory() is deprecated in Android 11 need alternative approach.

im using Pixel 3a where file chooser didnt show all files present in download folder

**Comment by Langstra** [comment]
I am sorry, but we're no longer supporting this plugin. Maybe another fork of the plugin can help or you could fork this one and fix it yourself.
